### ISSUE TITLE
Making image x86

### ISSUE THREAD

**Issue by mackjb** [ovh/overthebox-openwrt#1]
I'm quite new at this, not sure i did it well.
I try to build and generate overthebox-openwrt image for hosting it in VirtualBox. I build on debian Jesie without issue openwrt standard but this gitproject seems to needs Golang

It fails compiling with this issue

make[3]: Leaving directory '/home/mackjb/overthebox-openwrt/package/base-files'
make[3]: Entering directory '/home/mackjb/overthebox-openwrt/package/boot/grub2'
make[3]: Leaving directory '/home/mackjb/overthebox-openwrt/package/boot/grub2'
make[3]: Entering directory '/home/mackjb/overthebox-openwrt/package/boot/grub2'
make[3]: Leaving directory '/home/mackjb/overthebox-openwrt/package/boot/grub2'
make[3]: Entering directory '/home/mackjb/overthebox-openwrt/feeds/overthebox/bosun'
cd /home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0/cmd/scollector; GOPATH=/home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0 go build
# _/home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0/cmd/scollector

./main.go:299: syntax error: unexpected range, expecting {
./main.go:304: syntax error: argument to go/defer must be function call
./main.go:306: non-declaration statement outside function body
./main.go:307: syntax error: unexpected }
Makefile:59: recipe for target '/home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0/.built' failed
make[3]: **\* [/home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0/.built] Error 2
make[3]: Leaving directory '/home/mackjb/overthebox-openwrt/feeds/overthebox/bosun'
package/Makefile:191: recipe for target 'package/feeds/overthebox/bosun/compile' failed
make[2]: **\* [package/feeds/overthebox/bosun/compile] Error 2
make[2]: Leaving directory '/home/mackjb/overthebox-openwrt'
package/Makefile:188: recipe for target '/home/mackjb/overthebox-openwrt/staging_dir/target-x86_64_musl-1.1.10/stamp/.package_compile' failed
make[1]: **\* [/home/mackjb/overthebox-openwrt/staging_dir/target-x86_64_musl-1.1.10/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/mackjb/overthebox-openwrt'
/home/mackjb/overthebox-openwrt/include/toplevel.mk:181: recipe for target 'world' failed
make: **\* [world] Error 2

**Comment by mackjb** [comment]
After installing golang in testing mode, the compiler arrives to passes the error.
Probably a dependency of overthebox to add, and the specified version to precise.

**Comment by sduponch** [comment]
Hi,

I think your golang version is not up to date.

Best regards,
DUPONCHEEL Sébastien

**Comment by sduponch** [comment]
Yes, we plan to rewrite the Makefile to use gcc-go instead of a dirty 
"go build"

Best regards,
DUPONCHEEL Sébastien.

**Comment by simon** [comment]
fixed in https://github.com/ovh/overthebox-feeds/pull/140
