### ISSUE TITLE
x86-64 not bootable on MS-9803

### ISSUE THREAD

**Issue by debiansid** [ovh/overthebox-openwrt#16]
my computer is 965G mother board, which running openwrt trunk very smoothly, but when I tried to flash my own ovh-openwrt into it , it keeps crashing. and the same image I can run on esxi based virtual machine.

is there any way to fix it?

thanks

**Comment by sduponch** [comment]
Hi, can you explain how is it crashing with the error message (kernel panic, ...) ?

**Comment by debiansid** [comment]
Just nothing on display suddenly, LED display shows no signals

**Comment by debiansid** [comment]
FYI my CPU is core2 duo U7100 which does not have AES-NI

**Comment by simon** [comment]
we support only hardware that we tested.
