### ISSUE TITLE
Making image x86 next

### ISSUE THREAD

**Issue by mackjb** [ovh/overthebox-openwrt#2]
I try to build and generate overthebox-openwrt image for hosting it in VirtualBox. I build on debian Jesie without issue openwrt standard.

I have the issue that  It fails compiling with this error message :

install -m0755 ./files/scollector.config /home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0/ipkg-x86_64/bosun/etc/config/scollector
find /home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0/ipkg-x86_64/bosun -name 'CVS' -o -name '.svn' -o -name '.#_' -o -name '_~'| xargs -r rm -rf
Package bosun is missing dependencies for the following libraries:
libc.so.6
libpthread.so.0
Makefile:59: recipe for target '/home/mackjb/overthebox-openwrt/bin/x86/packages/overthebox/bosun_0.2.0-0.7_x86_64.ipk' failed
make[3]: **\* [/home/mackjb/overthebox-openwrt/bin/x86/packages/overthebox/bosun_0.2.0-0.7_x86_64.ipk] Error 1

When i look to the makefile, i have 
define Package/bosun
        SECTION:=utils
        CATEGORY:=OVH
        TITLE:=add bosum metric monitor
        DEPENDS:= +libc +libpthread
endef

If you have an idea that explains why it's not building i would appreciate your help on the subject.

Thx

PS: I speak french also if needed.

**Comment by benlo06** [comment]
Hello,
I have the same problem in compile, but image is compiled and avaiblable in
http://downloads.overthebox.ovh/trunk/x86/64/

Regards,
Benoit

**Comment by mackjb** [comment]
Hi,

Thanks for your return, i'm going to try these images.

Regards

On Sun, Oct 4, 2015 at 10:10 PM, Laurent notifications@github.com wrote:

> Hello,
> I have the same problem in compile, but image is compiled and avaiblable in
> http://downloads.overthebox.ovh/trunk/x86/64/
> 
> Regards,
> Benoit
> 
> Le 04/10/2015 20:05, mackjb a écrit :
> 
> > I try to build and generate overthebox-openwrt image for hosting it in
> > VirtualBox. I build on debian Jesie without issue openwrt standard.
> > 
> > I have the issue that It fails compiling with this error message :
> > 
> > install -m0755 ./files/scollector.config
> > 
> > /home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0/ipkg-x86_64/bosun/etc/config/scollector
> > find
> > 
> > /home/mackjb/overthebox-openwrt/build_dir/target-x86_64_musl-1.1.10/bosun-0.2.0/ipkg-x86_64/bosun
> > -name 'CVS' -o -name '.svn' -o -name '.#/' -o -name '/~'| xargs -r rm -rf
> > Package bosun is missing dependencies for the following libraries:
> > libc.so.6
> > libpthread.so.0
> > Makefile:59: recipe for target
> > 
> > '/home/mackjb/overthebox-openwrt/bin/x86/packages/overthebox/bosun_0.2.0-0.7_x86_64.ipk'
> > failed
> > make[3]: ***
> > 
> > [/home/mackjb/overthebox-openwrt/bin/x86/packages/overthebox/bosun_0.2.0-0.7_x86_64.ipk]
> > Error 1
> > 
> > When i look to the makefile, i have
> > define Package/bosun
> > SECTION:=utils
> > CATEGORY:=OVH
> > TITLE:=add bosum metric monitor
> > DEPENDS:= +libc +libpthread
> > endef
> > 
> > If you have an idea that explains why it's not building i would
> > appreciate your help on the subject.
> > 
> > Thx
> > 
> > PS: I speak french also if needed.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ovh/overthebox-openwrt/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ovh/overthebox-openwrt/issues/2#issuecomment-145384004
> .

## 

Cordialement
MACK Jean Baptiste

**Comment by sduponch** [comment]
http://downloads.overthebox.ovh/trunk/x86/64/

You can find a precompiled VDI image from here.

**Comment by GinesGarcia** [comment]
Hi,
i'm trying to use the vdi image creating a new machine on VBox but a black screen is shown. I'm using the "Linux 2.6/3.x/4.x(32 bit)" option, should i use other Operating system option? maybe other additional options??

thanks in advance

**Comment by mackjb** [comment]
You have to use the 64bit versions.

On Tue, Oct 6, 2015 at 3:12 PM, Ginés García Avilés <
notifications@github.com> wrote:

> Hi,
> i'm trying to use the vdi image creating a new machine on VBox but a black
> screen is shown. I'm using the "Linux 2.6/3.x/4.x(32 bit)" option, should i
> use other Operating system option? maybe other additional options??
>
> thanks in advance
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ovh/overthebox-openwrt/issues/2#issuecomment-145852284>
> .
>



-- 
Cordialement
MACK Jean Baptiste

**Comment by chruldt** [comment]
I get exactly the same error on mips32...

**Comment by BenJule** [comment]
Hmmm any solution?

**Comment by manu67a** [comment]
Hi,

I have created my own image due to missing network drivers and all compiles fine.
In case you need one, I have a .53 version available.

**Comment by BenJule** [comment]
Need an Image for my https://wiki.openwrt.org/toh/hwdata/tp-link/tp-link_tl-wr1043nd

**Comment by chruldt** [comment]
Without bosun and overthebox it compiles but there doesn't seem to be any traces of mptcp?

**Comment by sduponch** [comment]
Maybe you did not have the good branch.

```
 git clone https://github.com/ovh/overthebox-openwrt.git -b overthebox
 cd overthebox-openwrt
 ./scripts/feeds update -a
 ./scripts/feeds install -a -p overthebox
 ./scripts/feeds install -p overthebox -f netifd
 ./scripts/feeds install -a
 cp _.config.DE3815TYKE .config
 make menuconfig
 make V=s -j9
```

Best regards,
DUPONCHEEL Sébastien

**Comment by BenJule** [comment]
Bonjour Sébastien,

Is overthebox still working with ar71xx tl-wr1043ndv1?

Greetz
/Ben

**Comment by sduponch** [comment]
OverTheBox is mainly designed to run on x86 Nuc with AES-NI, but it 
could be ported on any device having AES accelerator (excluding golang 
bossun package).

I think ar71xx is not powerfull enougth to support OverTheBox at full 
speed (i expect 6Mbits max).
Currently, i am porting it on ARMv8 based device like Nvidia Shield tv 
(Jetson X1).

Best regards,
DUPONCHEEL Sébastien.

**Comment by manu67a** [comment]
@BenJule ,

Still need an image for ar71xx ?
If yes pick below the one you need and I send it here if possible:

openwrt-ar71xx-nand-r6100-initramfs-uImage.bin
openwrt-ar71xx-nand-R6100-rootfs.tar.gz
openwrt-ar71xx-nand-rootfs.cpio.gz
openwrt-ar71xx-nand-uImage-gzip.bin
openwrt-ar71xx-nand-uImage-initramfs-gzip.bin
openwrt-ar71xx-nand-uImage-initramfs-lzma.bin
openwrt-ar71xx-nand-uImage-lzma.bin
openwrt-ar71xx-nand-vmlinux.bin
openwrt-ar71xx-nand-vmlinux.elf
openwrt-ar71xx-nand-vmlinux.gz
openwrt-ar71xx-nand-vmlinux-initramfs.bin
openwrt-ar71xx-nand-vmlinux-initramfs.elf
openwrt-ar71xx-nand-vmlinux-initramfs.gz
openwrt-ar71xx-nand-vmlinux-initramfs.lzma
openwrt-ar71xx-nand-vmlinux-initramfs-lzma.elf
openwrt-ar71xx-nand-vmlinux.lzma
openwrt-ar71xx-nand-vmlinux-lzma.elf

Rgds

Manu

**Comment by chruldt** [comment]
@Sébastien, yes, a fresh checkout did compile, now I just try to make it small enough for my tp wdr4300 :-)

**Comment by BenJule** [comment]
@chruldt please let me know, when ure WDR4300 is running fine!
@manu67a its possible to upgrade my openwrt with your Images?

Greetz
Ben

**Comment by manu67a** [comment]
@BenJule, yes sure, just let me know the files you need so I can send it where you need it.

**Comment by BenJule** [comment]
@manu67a ar71xx-tl-wr1043ndv1-squashfs-upgrade.bin

**Comment by chruldt** [comment]
@BenJule, I got it small enough, it's running fine but there is no /proc/sys/net/mptcp which makes me believe I killed mptcp even though it's ticked in make menuconfig and in make kernel_menuconfig ...

**Comment by simon** [comment]
@chruldt do you use the 3.18-20 kernel ? we added mptcp for 3.18 kernel only : 
https://github.com/ovh/overthebox-openwrt/blob/overthebox/target/linux/generic/patches-3.18/000-mptcp-v3.18.20-d9f79bfb58af.patch

**Comment by sduponch** [comment]
Make sure you are in the 'overthebox' branch 
(https://github.com/ovh/overthebox-openwrt/tree/overthebox).

**Comment by chruldt** [comment]
Hmm, I was sure I was in the right branch but uname says linux 4.1...

**Comment by BenJule** [comment]
## Image

(http://downloads.overthebox.ovh/trunk/x86/64/openwrt-x86-64-combined-ext4.vdi)

## Virtualbox Settings
1. Network with 2 devices
   - device 1 Networkbridge
   - device 2 Intern Network
2. Storage Type
   - IDE Controller removed
   - Added SATA Controller and link to .vdi image

## OpenWRT Bootsequence

OpenWRT Boot: ![Alt Text](http://puu.sh/mBwcD/80c138b616.png)

After hit ENTER: ![Alt Text](http://puu.sh/mBwvD/f50137f0f9.png)

ifconfig eth0: ![Alt Text](http://puu.sh/mBwEe/72e7bb2de2.png)

ifconfig if0: ![Alt Text](http://puu.sh/mBxlp/be8be20990.png)

ifconfig if1: ![Alt Text](http://puu.sh/mBxox/b801db79cb.png)

Any idea why isnt luci working? I can only ping the vm ip!

**Comment by sduponch** [comment]
Hi,

Do you have a lan interface ?

If not, try to add the follwing cfg in /etc/config/network and reboot.

config interface 'lan'
         option multipath 'off'
         option ifname 'lan'
         option type 'macvlan'
         option interface 'eth0'
         option proto 'static'
         option ipaddr '192.168.0.10'
         option netmask '255.255.255.0'
         option metric '0'

Best regards,
DUPONCHEEL Sébastien

**Comment by sduponch** [comment]
You can also try to swap macvlan master interface from eth0 to eth1 
(except for if1)

**Comment by BenJule** [comment]
okay the ping to (x.tld) & (all int ip) is working now! If i open Webbrowser like (192.168.1.15) i get an ERR_CONNECTION_TIMED_OUT!

**Comment by BenJule** [comment]
nothing! if i switch from Bridged to NAT, virtualbox is starting openwrt in read only!

**Comment by silopolis** [comment]
Hi, just beginning to play with OverTheBox under VirtualBox so, first, big thanks goes to OVH for making this FOSS and to the smart folks at hand there !

As I could as easily have spent hours on this, it may be good to mention somewhere that the IDE controler should be removed and the VHD configured on a SATA controler to avoid the boot to freeze at "Switched to clocksource tsc".

Thanks again for all.
