### ISSUE TITLE
add filter aaaa for dnsmasq; Does this work with the latest dnsmasq?

### ISSUE THREAD

**Issue by rugabunda** [ovh/overthebox-openwrt#27]
I'd like to block AAAA but this is a 3 year old patch; Is it compatible? Thanks!!

**Comment by rugabunda** [comment]
https://github.com/ovh/overthebox-openwrt/commit/2c46395abf00fd47c14909d5ac844c2e571dcc7a#diff-aaad9bf958365b7e90893bd4feb344ee

**Comment by angt** [comment]
Hi,
This patch is still valid but it needs some work to adapt to other versiosn, for 2.78 we use this one: https://raw.githubusercontent.com/ovh/overthebox-feeds/master/dnsmasq/patches/310-dns-filter-aaaa.patch
Regards
