### ISSUE TITLE
Making an overthetop image for a WRT610N router - 

### ISSUE THREAD

**Issue by thefrenchgoofy** [ovh/overthebox-openwrt#3]
Hi,

I cannot complete the image for the following reason:
install -m0755 ./files/scollector.config /home/osboxes/overthebox-openwrt/build_dir/target-mipsel_mips32_musl-1.1.11/bosun-0.4.0/ipkg-brcm47xx/bosun/etc/config/scollector
**find /home/osboxes/overthebox-openwrt/build_dir/target-mipsel_mips32_musl-1.1.11/bosun-0.4.0/ipkg-brcm47xx/bosun -name 'CVS' -o -name '.svn' -o -name '.#_' -o -name '_~'| xargs -r rm -rf
Package bosun is missing dependencies for the following libraries:
libc.so.6
libpthread.so.0**
Makefile:59: recipe for target '/home/osboxes/overthebox-openwrt/bin/brcm47xx/packages/overthebox/bosun_0.4.0-0.8_brcm47xx.ipk' failed
make[3]: **\* [/home/osboxes/overthebox-openwrt/bin/brcm47xx/packages/overthebox/bosun_0.4.0-0.8_brcm47xx.ipk] Error 1
make[3]: Leaving directory '/home/osboxes/overthebox-openwrt/feeds/overthebox/bosun'
package/Makefile:191: recipe for target 'package/feeds/overthebox/bosun/compile' failed
make[2]: **\* [package/feeds/overthebox/bosun/compile] Error 2
make[2]: Leaving directory '/home/osboxes/overthebox-openwrt'
package/Makefile:188: recipe for target '/home/osboxes/overthebox-openwrt/staging_dir/target-mipsel_mips32_musl-1.1.11/stamp/.package_compile' failed
make[1]: **\* [/home/osboxes/overthebox-openwrt/staging_dir/target-mipsel_mips32_musl-1.1.11/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/osboxes/overthebox-openwrt'
/home/osboxes/overthebox-openwrt/include/toplevel.mk:177: recipe for target 'world' failed
make: **\* [world] Error 2

I am attaching my config in case it will give you some hints about what I am doing wrong. 
[WRT610N.config.txt](https://github.com/ovh/overthebox-openwrt/files/37182/WRT610N.config.txt)

**Comment by sduponch** [comment]
Hello,

As gccgo is not updated to 1.5.2 yet, bossun is only compatible with 
x86. just unselect bossun from .config and recompile.

Best regards,
DUPONCHEEL Sébastien
