### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by therealjackburke** [ovh/overthebox-openwrt#4]
Hello,

Is there a plan to release the server configuration if I want to use my own dedicated server?

Thank you.

**Comment by mhoungbo** [comment]
me too

**Comment by therealjackburke** [comment]
It's not actually that difficult.. You can set up the server by connecting with openvpn or vtun and using a socks proxy like dante.

**Comment by mhoungbo** [comment]
thanks

**Comment by olaulau** [comment]
Did somebody succeed in the server part on a dedicated server ? any info / doc ?

**Comment by segobi** [comment]
Id also like to use the openwrt system using my own dedicated server...
any progress ?

**Comment by segobi** [comment]
I guess you could set the environment variables and start the appropriate services but it would be more like a hack... Id like the system work as a whole...

**Comment by segobi** [comment]
Got it working

**Comment by olaulau** [comment]
can you describe how ?

**Comment by segobi** [comment]
ok ill write a tutorial

**Comment by debiansid** [comment]
Cannot wait for it

**Comment by debiansid** [comment]
Still waiting your tutorial

**Comment by debiansid** [comment]
My OVB stucks at OverTheBox DHCP,how get through it?

**Comment by n0rad** [comment]
@segobi, I also would like to see a tuto to setup the server part, thx

**Comment by debiansid** [comment]
@segobi I want to deploy OTB in a x86 computer has 2 Ethernet ports with a Modem in bridge mode. I am wondering how to setup in this scenario . And I have VPS running shadowsocks server.

**Comment by debiansid** [comment]
`Socks` `service` `is` `not` `runningTUN` `service` `is` `not` `running`

now I got this

**Comment by simon** [comment]
we don't plan to release server configuration to use on your dedicated server.

**Comment by n0rad** [comment]
And the open source argument just went away...
