### ISSUE TITLE
Testing Virtualbox precompiled image

### ISSUE THREAD

**Issue by paketecuento** [ovh/overthebox-openwrt#8]
Hi, I downloaded [Virtualbox image](http://downloads.overthebox.ovh/trunk/x86/64/openwrt-x86-64-combined-ext4.vdi). After following the steps detailed in the [official doc](https://www.ovh.com/fr/g2281.tester_overthebox_sur_virtualbox), the system looks to boot ok. Several interfaces are created:

![screen shot 2016-06-29 at 22 27 24](https://cloud.githubusercontent.com/assets/5316182/16467714/dcd96f98-3e48-11e6-8fe5-a7a4c4ca9de9.png)
![screen shot 2016-06-29 at 22 27 38](https://cloud.githubusercontent.com/assets/5316182/16467720/e36f1f60-3e48-11e6-81fb-c5339f597984.png)

![screen shot 2016-06-29 at 23 59 32](https://cloud.githubusercontent.com/assets/5316182/16470284/978d76ac-3e55-11e6-982e-a11f02e6231d.png)

But cannot ping internet nor the gateway :(. Of course https://overthebox.ovh, 192.168.1.23 and 192.168.1.21 are not accesible. Any idea??

thanks

**Comment by mwetterw** [comment]
Hi,

You may need to activate promisc mode in hardware + software in order for macvlan emulation to work properly.

### Hardware side

`VBoxManage modifyvm TheVM --nicpromisc1 allow-all`

Or use the GUI to enable it.

### Software side

`sed -i '/exit 0/i ip link set dev eth0 promisc on' /etc/rc.local`

Then reboot the VM.
